### PR TITLE
Code refactor

### PR DESCRIPTION
**Pull request by gastsail**
I have cleaned the code in LibrariesFragment, I will keep cleaning the other classes but I want to push in the time I can the different refactors to keep track of each refactor change

**What this commit contains** 🚀 
- LibrariesFragment has been cleaned for better understanding
- ProjectSyncFragment has been cleaned for better understanding
- NotificationsFragment has been cleaned for better understanding
- UpdatesFragment has been cleaned for better understanding
- It uses viewmodel delegation for the instances making it simpler
- It fixes some lifecycle issues while refreshing the list
- It removed unnecessary activity scoping for certain operations
- MainActivity now has a listener that knows about the destinations to hide the fab button instead of needed to be done in the fragments
- Gradle has added the safe args kotlin plugin instead of the default one
- Changed the way viewmodel handle jobs by using viewModelScope that takes cares of viewmodel lifecycle

### CODE REVIEW

**Comment by gastsail** [comment]
Excellent! Love the movement of the master from the clean-up branch, are you merging this there so I can pull from the source and continue?

Thanks for the feedback @lmj0011 🚀

**Comment by lmj0011** [comment]
>are you merging this there so I can pull from the source and continue?

Is there a problem with you continuing on the branch you already created? I don't plan on adding anything to master anytime soon so you don't have to worry about any conflicts.

I plan to review once you're done with all of the refactor work you sought out to do.

@gastsail

**Comment by gastsail** [comment]
Yep, I mean merging to the current clean-up branch not master , this is because I don't want to have inconsistencies in the branch and keep it updated with each PR

**Comment by lmj0011** [comment]
>this is because I don't want to have inconsistencies in the branch and keep it updated with each PR

What inconsistencies? I'm not going to keep merging your changes piecemeal. Do all your work on your branch and then I will review it. Keep yourself updated by breaking your work up with commits and updating this PR like you did with the first commit.

**Comment by gastsail** [comment]
I have cleaned all the UI package for better understanding, sorry for the confusion about the merging, you can review these changes, have a nice day

**Comment by gastsail** [comment]
Hi, how are you :) any update on this PR ?

**Comment by lmj0011** [comment]
@gastsail working on other things. 
This PR is not a priority, so it won't be anytime soon that I actually review/test it.

thanks for the taking time to do this though.

**Pull request merged**
